# Generated by Django 2.2 on 2019-04-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('initiative', 'name')},
        ),
    ]
